version: 1
# amqp config for connecting to amqp server
amqp:
  host: "localhost"
  port: 5672
  user: "guest"
  password: "guest"

# amqp url has higher priority than amqp config object
amqpUrl: ''

# AppId Host Map is a mapping that used for JobExecutor or JobScheduler to replace the access url from the message
# the remote url will be replaced with host defined in the mapping. there is no default value, if appid is not found,
# no replacement will occur.
appIdHostMap:
  test_download_manager: "http://localhost:8000/"

# Config Below is for JobExecutor
# support variable:
#   ${cwd}: current working directory
#   ${home}: user's home directory
#   ${project_root}: project's root directory
# the job executor profile path, default is ~/.mira/video-manager
jobExecProfileDir: "${project_root}/temp"

# the job executor's temp directory for copied/downloaded video files, default is ${jobExecProfileDir}/temp
videoTempDir: "${project_root}/temp/video"

# the maximum execution time of a job, a job will be rescheduled if it exceeds the maximum time. unit is minutes
maxJobProcessTime: 300

# How long will the job executor keep processed files and downloaded files for successful jobs
fileRetentionDays: 3

# How long will the job executor keep processed files and downloaded files for failed jobs
failedFileRetentionDays: 10

# how many threads can ffmpeg use for encoding, it should be less than your cpu cores, if the value is 0, then no limit is added
# if the value is negative. then it will use (<logical cores> - maxThreadsToProcess) threads
maxThreadsToProcess: -1

# used for composing the url for downloading output file from job executor, default is http://localhost:8000/output/
WebServer:
  enableHttps: false
  host: "localhost"
  port: 8082

ApiWebServer:
  enableHttps: false
  host: "localhost"
  port: 8083

# base path for job log.
jobLogPath: '/var/log/mira-video-manager/jobs'