name: Docker Image CI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  release-package:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Sentry CLI
      run: curl -sL https://sentry.io/get-cli/ | bash
    - name: Create a release
      run: |
        export VERSION=mira-video-manager@$(git describe --tags)
        sentry-cli releases -o ${{ secrets.SENTRY_ORG }} new -p ${{ secrets.SENTRY_PROJECT }} $VERSION --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }}
        sentry-cli releases -o ${{ secrets.SENTRY_ORG }} set-commits -p ${{ secrets.SENTRY_PROJECT }} --auto $VERSION --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }}

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: irohalab/mira-video-manager
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        buildoptions: "--target prod"
        # registry: docker.pkg.github.com
        tag_names: true

    - name: Finalize release
      run: |
        export VERSION=indexer@$(git describe --tags)
        sentry-cli releases -o ${{ secrets.SENTRY_ORG }} finalize -p ${{ secrets.SENTRY_PROJECT }} --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }} $VERSION
