name: Docker Image CI

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  release-package:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Sentry CLI
      run: curl -sL https://sentry.io/get-cli/ | bash
    - name: Create a release
      run: |
        export VERSION=mira-video-manager@$(git describe --tags)
        sentry-cli releases -o ${{ secrets.SENTRY_ORG }} new -p ${{ secrets.SENTRY_PROJECT }} $VERSION --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }}
        sentry-cli releases -o ${{ secrets.SENTRY_ORG }} set-commits -p ${{ secrets.SENTRY_PROJECT }} --auto $VERSION --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }}

    - uses: pmorelli92/github-container-registry-build-push@2.0.0
      name: Build and Publish latest service image
      with:
        github-push-secret: ${{ secrets.GITHUB_TOKEN }}
        docker-image-name: mira-video-manager
        docker-image-tag: ${{ github.ref_name	}} # optional
        # dockerfile-path: ./src/svc/Dockerfile # optional
        # build-context: ./src/svc # optional

    - name: Finalize release
      run: |
        export VERSION=indexer@$(git describe --tags)
        sentry-cli releases -o ${{ secrets.SENTRY_ORG }} finalize -p ${{ secrets.SENTRY_PROJECT }} --auth-token ${{ secrets.SENTRY_AUTH_TOKEN }} $VERSION
